### ISSUE TITLE
[Feat]: Undersøke hvordan man kan prodsette dokumentasjonen

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-frontend#101]
## 🚀 Feature forespørsel

- [ ] Undersøk CMS - skal vi ha det eller ikke?
- [ ] Ønsker vi å fortsette å bruke strapi?
- [ ] Driftsmeldinger ?
- [ ] Hvordan skal dokumentasjonen komme ut på data.norge.no?
- [ ] Ønske: man må ikke være utvikler for å kunne oppdatere dokumentasjonen
- [ ] Lage issues for teknisk implementasjon
- [ ] Undersøk hvordan Altinn har løst det

**Comment by terjesyl** [comment]
@KjerstiSteien 
Denne er ish løst nå.

- Vi prodsetter dokumentasjon med mdx i frontend.
- Vi bruker Strapi som CMS for bilder og media.


- Driftsmeldinger må avklares.
- Etterhvert bør vi flytte dokumentasjonstekstene (`mdx`-filene) over i et eget repo, utenfor fdk-frontend. Vil senke terskelen for ikke-tekniske mtp. å redigere innholdet.
