### ISSUE TITLE
[Feat]: Kvalitetssjekke og oppdatere dokumentasjon "Hva er data.norge.no"

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-frontend#116]
- Legges inn i repo [Docs](https://github.com/pooriamehregan/docs)
- https://data.norge.no/about
- https://informasjonsforvaltning.github.io/

- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

<img width="786" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-frontend/assets/48259307/fa65907b-7403-496d-a17c-04bb62cc35fd">

**Comment by terjesyl** [comment]
Oppretter dokument i docs-repoet til Pooria som vi kan skrive på i fellesskap:)

**Comment by hegeaal** [comment]
I prod https://data.norge.no/about
