### ISSUE TITLE
[Feat]: Dokumentasjon "Hvordan publisere metadata?"

### ISSUE THREAD

**Issue by hegeaal** [Informasjonsforvaltning/fdk-frontend#118]
https://data.norge.no/getting-started/finding-data
- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

https://data.norge.no/getting-started/publishing-intro
- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

https://data.norge.no/getting-started/creating-descriptions-self
- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

https://data.norge.no/getting-started/publishing-descriptions
- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

https://data.norge.no/getting-started/creating-descriptions-registration
- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

https://data.norge.no/getting-started/triggering-harvest
- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

https://data.norge.no/getting-started/resources
- [x] Norsk bokmål
- [x] Norsk nynorsk
- [x] Engelsk

Nice-to-have (vurdere til senere)
- Egen side for å beskrive kravene til datakilden/høsteendepunktet (?)
- https://www.digdir.no/datadeling/dele-data-med-andre/2252

<img width="827" alt="image" src="https://github.com/Informasjonsforvaltning/fdk-frontend/assets/48259307/0d45d6d8-3077-4eb6-afc9-226bb6300228">

![image](https://github.com/Informasjonsforvaltning/fdk-frontend/assets/48259307/2dd2f524-16b1-4651-82cb-0fb088754b2a)

**Comment by terjesyl** [comment]
Utkast ligger her: https://github.com/fellesdatakatalog/info-pages-playground/tree/2-utkast/hvordan-publisere

**Comment by terjesyl** [comment]
Da er oversettelsene ute. Foreslår vi lukker dette issuet, så kan vi heller fikse i innholdet etterhvert som vi får tilbakemeldinger. Hva tenker du @hegeaal

**Comment by hegeaal** [comment]
Enig! Dokumentasjonen kan sees her: https://data.norge.no/getting-started/publishing-intro
