### ISSUE TITLE
Oppdatere metadata på data.norge.no

### ISSUE THREAD

**Issue by Lillebo** [Informasjonsforvaltning/fdk-frontend#159]
Vår nåværende metadata for data.norge.no er følgende:

**Tittel:**
>Felles datakatalog - Norge.no

**Beskrivelse:** (288 tegn)
>data.norge.no er det offentlige nettstedet som gir oversikt over beskrivelser av datasett, begrep, api-er og informasjonsmodeller. Innholdet blir levert av ulike virksomheter, offentlige og private. Det er Digitaliseringsdirektoratet som er ansvarlig for drift og utvikling av nettstedet.

Som blir vist (avkuttet) på Google slik:

<img width="639" alt="Screenshot 2024-08-15 at 13 03 02" src="https://github.com/user-attachments/assets/4d9cd96b-9845-4780-a181-e80ee04b747b">

Dette kommer av at Google har en begrensning på ca. 160 tegn på hvor mye av beskrivelsen de viser i søkeresultatene.

Jeg har litt lyst til å endre tittel og beskrivelse til dette:

**Tittel:** 
>data.norge.no - &lt;sidenavn&gt;

**Beskrivelse:** (nøyaktig 160 tegn)
>data.norge.no er Norges offisielle portal for deling av data fra offentlige og private virksomheter som du kan bruke til å lage tjenester eller drive forskning.

Som forhåpentligvis da vil vises på Google slik:

<img width="623" alt="Screenshot 2024-08-15 at 13 10 35" src="https://github.com/user-attachments/assets/9ce63296-9a88-4182-a5b8-3d08ca1f4fa2">

**Comment by terjesyl** [comment]
Veldig bra catch! Hva tenker du @KurtStian , er det dekkende?

**Comment by KurtStian** [comment]
@terjesyl 
Jeg tenker det er en bra salgspitch for å få folk til å sjekke løsningen. 

Siden det er begrensning på antall tegn tror jeg det ikke mulig å legge til informasjon som gjør det helt dekkende.
At man som regel ikke finner selve dataene i løsningen, men kun beskrivelse av dataene og informasjon om hvordan man kan få tak i dem (og etter hvert lenke til søknadsløsning) , og at enkelte data kanskje er "lukket/har juridiske begrensninger" er jo noe de finner ut når de er inne i løsningen :-)

Så jeg gir 👍 på forslaget. Godt jobbet @Lillebo

**Comment by Lillebo** [comment]
Topp, da prøver vi dette 😊
