### ISSUE TITLE
Forslag til endring på siden additional-resources.mdx

### ISSUE THREAD

**Issue by KurtStian** [Informasjonsforvaltning/fdk-frontend#189]
Under spesifikasjoner:

Forslag til ny tekst - nynorsk:
Data.norge.no baserer seg på flere standarder og spesifikasjoner. Kva standard/spesifikasjon du skal bruke avhenger av typen ressurs (datasett, omgrep, teneste, osv.) du skal beskrive.

Forslag til ny tekst - bokmål:
Data.norge.no baserer seg på flere standardar og spesifikasjonar. Hvilken standard/spesifikasjon du skal bruke kommer an på hvilken type ressurs (datasett, begrep, tjeneste, osv.) du skal beskrive.

Forslag til ny tekst - engelsk:
Data.norge.no relies on several standards and specifications. Which standard/specification you should use depends on the type of resource (dataset, concept, service, etc.) you are describing.

Skrive hele navnet på standardene/spesifikasjonene. Forslag bokmål

- [Standard for beskrivelse av datasett, datatjenester og datakataloger (DCAT-AP-NO)](https://data.norge.no/specification/dcat-ap-no)
- [Forvaltningsstandard for begrepsbeskrivelser (SKOS-AP-NO-Begrep)](https://data.norge.no/specification/skos-ap-no-begrep)
- [Spesifikasjon for beskrivelse av informasjonsmodeller (ModellDCAT-AP-NO)](https://data.norge.no/specification/modelldcat-ap-no)
- [Spesifikasjon for tjeneste- og hendelsesbeskrivelser (CPSV-AP-NO)](https://data.norge.no/specification/cpsv-ap-no)

Nynorsk:

- [Standard for beskriving av datasett, datatenester og datakatalogar (DCAT-AP-NO)](https://data.norge.no/specification/dcat-ap-no)
- [Forvaltningsstandard for beskriving av omgrep (SKOS-AP-NO-Begrep)](https://data.norge.no/specification/skos-ap-no-begrep)
- [Spesifikasjon for beskriving av informasjonsmodellar (ModellDCAT-AP-NO)](https://data.norge.no/specification/modelldcat-ap-no)
- [Spesifikasjon for beskriving av tenester og hendingar (CPSV-AP-NO)](https://data.norge.no/specification/cpsv-ap-no)

Engelsk:

- [The standard for describing datasets, data services og datacatalogs (DCAT-AP-NO)](https://data.norge.no/specification/dcat-ap-no)
- [The governance standard for concept descriptions
. (SKOS-AP-NO-Begrep)](https://data.norge.no/specification/skos-ap-no-begrep)
- [The specification for describing information models (ModellDCAT-AP-NO)](https://data.norge.no/specification/modelldcat-ap-no)
- [The specification for describing services and events (CPSV-AP-NO)](https://data.norge.no/specification/cpsv-ap-no)

Under Verktøy Data.norge.no tilbyr - legg til:

- [atalsdcat](https://github.com/Informasjonsforvaltning/atlasdcat): Python-bibliotek som mapper Apache Atlas Glossary terms til DCAT metadata og omvendt.

Forslag om å lenke til kontak oss-siden:

Kommer du over feil eller mangler i disse, opprett gjerne et issue i repoet eller [Kontakt oss](.../contact)

**Comment by terjesyl** [comment]
Vi har snakket tidligere om bruke kun ordet spesifikasjon siden det dekker både spesifikasjoner og spesifikasjoner som har blitt standardisert. Skal vi bruke både spesifikasjon og standard her, eller blir det mer forvirrende for brukeren?

**Comment by terjesyl** [comment]
Ved nærmere ettertanke, når vi skriver ut det fulle navnet brukes begge ord, så da er det like greit å bruke begge i den innledende teksten også.
