### ISSUE TITLE
Fjerne ikoner på datakatalogene

### ISSUE THREAD

**Issue by Lillebo** [Informasjonsforvaltning/fdk-frontend#191]
### Nåværende:
<img width="1074" alt="Screenshot 2024-09-15 at 18 53 10" src="https://github.com/user-attachments/assets/a4a35e61-e327-4333-9a35-7d1496a4cbb7">

### Forslag:
<img width="1101" alt="Screenshot 2024-09-15 at 18 53 30" src="https://github.com/user-attachments/assets/302f53e8-b1fa-4c13-8b71-12f0bc805c59">

**Comment by Lillebo** [comment]
Vi kan godt fjerne ikonene for min del hvis de ikke er ønskelig, men jeg synes kanskje at de bidrar ganske bra til å kunne skille de ulike informasjonstypene fra hverandre.

Jeg tror de vil være til stor hjelp på f.eks. søke-siden når vi skal vise søketreff fra flere kataloger samtidig, hvor ikoner kan gjøre det enklere for brukeren å scanne resultatene kjappere. Datasett-ikonet brukes allerede til dette i resultatene under KI-søket:

<img width="722" alt="Screenshot 2024-09-15 at 19 01 25" src="https://github.com/user-attachments/assets/35588cf4-6185-443f-824f-56d06a4d3b68">

Husk at vi allerede har forenklet ganske mye ved å fjerne farge-kodene som eksisterer i gammel løsning.

**Comment by KjerstiSteien** [comment]
Hvis vi skal ha ikoner, så bør vi bruke litt tid på å finne ikoner som er entydige og standard for de katalogene vi ønsker å beskrive. Noen av dem er uproblematiske, men API og tjenester er jeg litt usikker på API vises ofte som tannhjul. Kanskje vi kan spille nye ikoner til aksel før vi gjeninnfører ikoner på data.norge.no? Jeg vil veldig gjerne brukerteste nye ikoner før vi tar dem i bruk.

**Comment by Lillebo** [comment]
Helt greit 👍 Da fjerner vi ikonene inntil videre, og plukker opp tråden igjen senere heller.

Jeg ser at både vi og andre har brukt tannhjul for å illustrere API tidligere, men jeg synes kanskje det kan være litt upresis bildebruk. Da foretrekker jeg å reservere tannhjul/gears for å illustrere innstillinger eller valgmuligheter.

Tanken bak det nye API-ikonet var å understreke at dette er mer direkte relatert til programmering enn de øvrige katalogene. Derfor brukte jeg ikonet med angle brackets, som er ganske [veletablert for å illustrere kode](https://www.google.com/search?q=code+icon&sca_esv=2a83cd2c2809a61f&sca_upv=1&biw=1403&bih=828&udm=2&ei=IbLyZqy0JI-73APNjYehCQ&ved=0ahUKEwjsyMT0y9uIAxWPHXcKHc3GIZQQ4dUDCBA&uact=5&oq=code+icon&gs_lp=Egxnd3Mtd2l6LXNlcnAiCWNvZGUgaWNvbjIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgAQyBRAAGIAEMgUQABiABDIFEAAYgARI_ApQwwNY3AlwBHgAkAEBmAGWAaAB_wKqAQMzLjG4AQPIAQD4AQGYAgegAoECwgIKEAAYgAQYQxiKBcICBhAAGAcYHpgDAIgGAZIHATegB84R&sclient=gws-wiz-serp).

Tanken bak ikonet for tjenester og hendelser var å understreke at katalogen er et hjelpemiddel for å *finne frem* og *navigere* blant et ofte uoversiktelig offentlig tjenestetilbud. Derfor valgte jeg et kompass her.
