### ISSUE TITLE
Fjerne kunstig intelligens fra datakatalog-meny - passer ikke inn med de andre

### ISSUE THREAD

**Issue by Lillebo** [Informasjonsforvaltning/fdk-frontend#192]

**Comment by Lillebo** [comment]
Jeg har forståelse for at det er en teknisk forskjell mellom de øvrige datakatalogene og oversikten over KI-prosjekter i offentlig sektor. Men jeg tror vi gjør brukeren en stor tjeneste hvis vi prøver å skjerme dem litt fra disse tekniske distinksjonene.

Jeg mener de ulike datakatalogene og KI-oversikten bør presenteres i samme meny fordi alle sammen er **oversikter over katalogisert informasjon** som vi sitter på. De er alle innganger til den mest interessante informasjonen på data.norge.no. Og jeg er redd for at KI-oversikten raskt blir en annenrangs-borger i menystrukturen hvis vi holder den adskilt fra de andre katalogene.

Det viktigste for brukeren er at de enkelt kan finne den informasjonen de søker, og at vi fremmer en enkel og ryddig opplevelse. Husk at inngangen til KI-oversikten ikke går rett til selve katalogen, men til informasjonssiden om KI-oversikten, hvor det står følgende før brukeren kan klikke seg videre inn til dataene:

>Oversikten er ikke komplett og vi trenger din hjelp til å holde den oppdatert. Datainnsamlingen er ikke basert på rapportering, men direkte kontakt med antatte relevante aktører. Oversikten bygges ut fortløpende, og gir ikke muligheten til å trekke noen endelige konklusjoner.

Vi kan gjerne døpe om overskriften eller paraplyen disse menyvalgene blir presentert under fra "Våre datakataloger" til bare "Kataloger" eller "Oversikter" for å gjøre kategoriseringen mer korrekt og kanskje gjøre at det føles mer naturlig at disse valgene presenteres samlet?

**Comment by KjerstiSteien** [comment]
Jeg mener at KI-oversikten er litt på siden av hovedformålet, og at det derfor er ok om den ikke vises først. Kunne den vært vist på linje med verktøy? Virksomhetsoversikten er også en strukturert mengde data, som kanskje ligner mer på KI-oversikten. Hvis vi endrer til oversikter, er jeg mer komfortabel med å vise den sammen med katalogene. Men jeg er fortsatt litt usikker på om den hører hjemme hos oss i det hele tatt.

**Comment by Lillebo** [comment]
Virksomhetsoversikten er også en slags katalog, men den er først og fremst et oppslagsverk for innholdet i de andre katalogene. Hvis vi skal fortsette å tilby en oversikt over KI-prosjekter så tenker jeg også at det ville vært naturlig å utvide Virksomhetsoversikten med en ekstra kolonne hvor man også ser antall KI-prosjekter den enkelte virksomheten er oppført med. Dette synes jeg understøtter tanken om at KI-oversikten bør presenteres sammen med de andre katalogene i menyen generelt.

<img width="1235" alt="Screenshot 2024-09-25 at 09 29 25" src="https://github.com/user-attachments/assets/a2028f9d-a3f8-4115-a6c8-a2414cafe23c">

Jeg tror også det kan ha god effekt å endre overskriftene disse presenteres under:

<img width="822" alt="Screenshot 2024-09-25 at 09 41 07" src="https://github.com/user-attachments/assets/824acd9d-76d7-4553-86a7-1b9b1b033dc0">

**Comment by KjerstiSteien** [comment]
Jeg synes ikke Kunstig intelligens oversikten passer inn med resten, så nå snur jeg igjen. Jeg synes vi skal degradere den til å ligge under verktøy for nå, så får vi heller se på hvordan vi skal løfte den frem senere. Det er noe helt annet enn resten og understøtter ikke datadeling på den måten de andre katalogene gjør. Jeg mener ki-oversikten per i dag bør sidestilles med virksomhetsoversikten. Kan ta en diskusjon på dette senere, når vi ser helhetlig på brukeropplevelsen. Men i dag synes jeg ikke den skal sidestilles med resten.

**Comment by Lillebo** [comment]
Ok, jeg gir meg :) Skal fikse 👍
