### ISSUE TITLE
Endre beskrivelser for katalogene

### ISSUE THREAD

**Issue by Lillebo** [Informasjonsforvaltning/fdk-frontend#193]
### Nåværende:

- Datasett: Samlinger av strukturert data som kan lastes ned eller aksesseres via APIer
- API-er: Protokoller for å kommunisere med datasystemer med dynamisk data og data i sanntid
- Begreper: Definisjoner og ordbøker på offisielle termer og begreper som virksomheter bruker i sine data
- Informasjonsmodeller: Strukturerte representasjoner av informasjon og data for datasett og APIer
- Tjenester og hendelser: Oversikt over tjenester, prosesser og hendelser som virksomheter bruker når de behandler data
- Kunstig intelligens: Oversikt over KI-prosjekter i offentlig sektor

### Forslag til nye:
- Datasett: Oversikt over samlinger av strukturert data som kan lastes ned eller aksesseres over.
- API-er: Oversikt over protokoller for å kommunisere med datasystemer med dynamiske data og data i sanntid.
- Begrep: Oversikt over begrep med tilhørende definisjoner og annen informasjon.
- Informasjonsmodeller: Oversikt over strukturerte representasjoner av informasjon og data for datasett og API-er.
- Tjenester og hendelser: Oversikt over tjenester som tilbys på vegne av offentlig sektor, og hendelser som kan utløse slike tjenester.

Tilsvarende på nynorsk og engelsk (si fra om du trenger oppdatert tekst her).

**Comment by Lillebo** [comment]
Hm, lurer litt på begrunnelsen for å legge til "Oversikt over..." forran beskrivelsene?

Tanken bak de nåværende beskrivelsene er å forklare brukeren **hva de vil finne** i de ulike katalogene. Jeg tenker kanskje det sier seg selv at en *katalog* er noe som gir *oversikt over* noe, og at dette ikke trenger å forklares? Derimot er det kanskje ikke like selvforklarende for alle brukerne hva et API er for noe.

### Ang. endringen på beskrivelsen for Begreper

>Begrep med tilhørende definisjoner og annen informasjon

Er dette fordi det ikke er riktig at katalogen inneholder ordbøker/glossary? Jeg tenker kanskje "annen informasjon" blir litt upresist/vagt her? Hva tenker dere om dette alternativet i så fall?

>Definisjoner på begreper som virksomheter bruker i sine data

### Ang. endringen på beskrivelsen for Tjenster og hendelser

>Tjenester som tilbys på vegne av offentlig sektor, og hendelser som kan utløse slike tjenester.

Stemmer det at denne katalogen kun inneholder tjenester fra offentlig sektor? I så fall er denne helt grei 👍

**Comment by KjerstiSteien** [comment]
> Hm, lurer litt på begrunnelsen for å legge til "Oversikt over..." forran beskrivelsene?
>
> Tanken bak de nåværende beskrivelsene er å forklare brukeren hva de vil finne i de ulike katalogene. Jeg tenker kanskje det sier seg selv at en katalog er noe som gir oversikt over noe, og at dette ikke trenger å forklares? Derimot er det kanskje ikke like selvforklarende for alle brukerne hva et API er for noe.


Opprinnelig var det både beskrivelser med og uten "Oversikt over". Så vi valgte en av dem, for å være konsekvent. @KurtStian kunne vi gått andre veien? 

I så fall blir det: 
Datasett: Samlinger av strukturert data som kan lastes ned eller aksesseres over.
API-er: Protokoller for å kommunisere med datasystemer med dynamiske data og data i sanntid.
Begrep: Begrep med tilhørende definisjoner og annen informasjon.
Informasjonsmodeller: Strukturerte representasjoner av informasjon og data for datasett og API-er.
Tjenester og hendelser: Tjenester som tilbys på vegne av offentlig sektor, og hendelser som kan utløse slike tjenester.

>Ang. endringen på beskrivelsen for Begreper
Begrep med tilhørende definisjoner og annen informasjon
>
>Er dette fordi det ikke er riktig at katalogen inneholder ordbøker/glossary? Jeg tenker kanskje "annen informasjon" blir litt upresist/vagt her? Hva tenker dere om dette alternativet i så fall?
>
>Definisjoner på begreper som virksomheter bruker i sine data

Definisjon er en del av informasjonen som er knyttet til begrepene, så det kan virke upresist for noen. Men jeg synes forslaget ditt kan fungere. I følge bokmålsordboka, er det "definisjon av begreper" som er riktig, så Vi kan endre til "Definisjoner av begreper som virksomheten bruker i sine data.

>Ang. endringen på beskrivelsen for Tjenster og hendelser
>Tjenester som tilbys på vegne av offentlig sektor, og hendelser som kan utløse slike tjenester.
>
>Stemmer det at denne katalogen kun inneholder tjenester fra offentlig sektor? I så fall er denne helt grei 👍

Den kan inneholde tjenester fra privat sektor, men disse tjenestene leveres på vegne av offentlig sektor. Derfor landet vi på den formuleringen.

**Comment by Lillebo** [comment]
Topp 👍 Da endrer jeg i henhold til dette 👆, hvis ikke @KurtStian har noen innvendinger? :)

**Comment by KurtStian** [comment]
Vi kan sikkert gå den andre veien. 

Beskrivelsen til datasett er vel ufullstendig: "Samlinger av strukturert data som kan lastes ned eller aksesseres over."

Beskrivelsen til tjenester/hendelse. Katalogen kan som Kjersti skriver inneholder tjenester som ikke er fra det offentlige, men man kan nok si at disse vil være på vegne av offentlig sektor av en eller annen grad. De "private" tjenestene er kun interessante når de er på vegne av det offentlige (private helse-/legtjenester, apotek, gravferd osv.) og når man tenker brukeren i sentrum og sammenhengende tjenester og livshendelser. Da vil også f.eks. bank- og forsikringstjenester kunne inngå selv om dette som regel noe som tilbys av privat sektor.
