### ISSUE TITLE
I infoboksen om KI-søk: "Vær obs på at KI-søket ikke alltid viser alle relevante treff."

### ISSUE THREAD

**Issue by Lillebo** [Informasjonsforvaltning/fdk-frontend#196]

**Comment by Lillebo** [comment]
Skal dette komme i stedet for, eller i tillegg til, setningen "Vær obs på at KI-søket kan inneholde feil"?

<img width="1145" alt="Screenshot 2024-09-15 at 22 46 04" src="https://github.com/user-attachments/assets/19463def-beb1-420b-accd-0c1f6616fcca">

**Comment by KjerstiSteien** [comment]
Vi tenkte i stedet for. Vi lurer også på om denne setningen burde vises i vanlig tekst og være en del av første avsnitt, sånn at setningen om personopplysninger kommer tydeligst frem. Vi mener dette er den viktigste informasjonen for brukeren. Så skjønner jeg at det har vært litt diskusjon rundt hva setningen om feil burde si. Her har ikke jeg veldig sterke meninger, så @KurtStian @jeffreiffers kan mene noe om dette om de vil.

**Comment by Lillebo** [comment]
Snakket litt med @KurtStian og @jeffreiffers om dette, hvor vi ble enige om å se på en litt annen formulering. Litt viktig å skille på betydningen av at resultatene er **1) ufullstendige** eller **2) upålitelige**.

Foreslår følgende omformulering:
>Vær obs på at KI-søket kan være både ufullstendig og inneholde feil.

Kan gjerne flytte setningen til første avsnitt og la teksten om personopplysninger stå alene med fet skrift 👍

**Comment by KjerstiSteien** [comment]
Støttes!
