### ISSUE TITLE
Oppdatere "Har du data å dele"-panelet

### ISSUE THREAD

**Issue by Lillebo** [Informasjonsforvaltning/fdk-frontend#200]
Gjelder denne:

<img width="1006" alt="Screenshot 2024-09-15 at 18 46 58" src="https://github.com/user-attachments/assets/139de60a-257a-4d24-bb3f-4c91b1accaa7">

- Kom i gang - endre lenke når ny dokumentasjon er på plass (Samme som Hvordan dele data i toppmenyen).
- Vi mener at vi ikke trenger Se dokumentasjon-knappen her. Den er for spesielt interesserte

**Comment by Lillebo** [comment]
Helt enig, men foreslår å endre til dette:

- Hovedhandling "Kom i gang" endres til "Del data" som peker til https://data.norge.no/publishing (akkurat som tilsvarende knapp i header)
- Sekundærhandling "Se dokumentasjon" endres til "Hjelp og veiledning" som peker til nye docs

<img width="1005" alt="Screenshot 2024-09-15 at 18 47 05" src="https://github.com/user-attachments/assets/8ade57f1-f0d4-47f2-b712-cc4d04ffc66d">

**Comment by terjesyl** [comment]
Mener vi her "Del data" eller "Del metadata/beskrivelser"? Bør skille mellom selve deling av data/datautveksling og synliggjøring av dataen i data.norge.no.

Kan formuleres på flere måter, det viktigste er at vi skiller mellom disse to ulike delene i den store prosessen som handler om både hvordan tilgjengeliggjøre og hvordan synliggjøre dataen.

**Comment by Lillebo** [comment]
Jeg forstår at det er en viktig teknisk forskjell mellom data og metadata her, men jeg mener vi gjør brukeren en tjeneste i å skjerme dem litt fra denne distinksjonen - i alle fall innledningsvis.

Hvis vi skal henge oss opp i å være påpasselig med å bruke "metadata" i stedet for "data" overalt, så er jeg redd vi kommer til å gå male oss selv opp i et litt vanskelig hjørne. Da blir vi raskt nødt til å også endre søkeknappen til "Finn metadata", bytte slagsord til "Der Norge deler metadata", bytte url til metadata.norge.no osv osv. Dette blir unødvendig vanskelig.

Måten data deles på data.norge.no er å dele metadata. Dette trenger ikke å forklares for brukeren før de begynner å lese dokumentasjonen på hvordan de faktisk kommer i gang og hvordan dette fungerer rent teknisk og i praksis. Men jeg er enig i at vi bør være tydelig på dette i selve dokumentasjonen. Her bør det komme veldig klart frem at det som faktisk deles er *metadata*, og at selve dataen ligger andre steder. Dette burde vi sikkert skrive allerede på [startsiden for "Dele data"-seksjonen](https://data.norge.no/nb/docs/sharing-data)?

**Comment by Lillebo** [comment]
Lukker denne som ferdig inntil videre. Også relatert til #198.
