### ISSUE TITLE
[Bug]: Lenke til "side om hvordan bruke koder" gir Page not found

### ISSUE THREAD

**Issue by AinaEngen** [Informasjonsforvaltning/fdk-frontend#231]
## 🐛 Bug rapport

Linken til "side om hvordan bruke koder" under Beskrive datasett gir "Page not found" (ligger litt langt ned på siden https://data.norge.no/nb/docs/how-to-guides/how-to-dataset/2-dataset-description)

![image](https://github.com/user-attachments/assets/d71d8dd7-3562-45f6-b70c-ab6a076739f9)

Får denne feilmeldinga:
![image](https://github.com/user-attachments/assets/85a4edb2-b1c3-42d4-99eb-b2967a439a3c)

**Comment by Anju023** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive
