### ISSUE TITLE
[Test]: Komponenttesting

### ISSUE THREAD

**Issue by pooriamehregan** [Informasjonsforvaltning/fdk-frontend#63]
### Feature beskrivelse
- komponenttesting: 
  - implemeter komponenttesting for komponentene i UI-biblioteket og det som ikke dekkes av E2E.
  - Storybook: sette opp storybook for komponentene

### Hvorfor trenger vi det?
Vi ønsker å oppdage feil tidlig ved å automatisere så mye som mulig.

### Forslag/løsning [Valgfritt]
- Jest
- React testing library 

### Definisjon av ferdig
- Alle UI-komopnenter har dedikerte tester

**Comment by Lillebo** [comment]
Løst av #75
